name: Validate

on:
  push:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install aiogithubapi==21.4.0

      - name: Install hassfest
        run: pip install hassfest

      - name: Hassfest validation
        run: hassfest .
